import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {chromium} from '../outputs/paper-reader/node_modules/@playwright/test/index.mjs';

const base='http://127.0.0.1:8766';
const docId='f9091cd15d594b599bcf882010ec1479';
const edge='C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe';
const browser=await chromium.launch({headless:true,executablePath:existsSync(edge)?edge:undefined});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
const api=async path=>{
  const response=await page.request.get(base+path);
  assert.equal(response.status(),200,path+': '+await response.text());
  return response.json();
};
const screenshot=name=>page.screenshot({path:fileURLToPath(new URL(name,import.meta.url))});
const baseline=await api('/api/documents/'+docId);
const layout=await api('/api/documents/'+docId+'/layout');
const fig=layout.objects.find(o=>o.page===1&&o.kind==='figure');
const table=layout.objects.find(o=>o.page===5&&o.kind==='table');
const details=await api('/api/documents/'+docId+'/objects/'+fig.id+'/details');
const tableDetails=await api('/api/documents/'+docId+'/objects/'+table.id+'/details');
assert.equal(details.marks.length,43);
assert.equal(details.tokens.length,69);
assert.equal(tableDetails.cells.filter(c=>!c.header).length,90);
assert.equal(tableDetails.cells.filter(c=>c.header).length,11);
const anchorFrom=async action=>{
  const responsePromise=page.waitForResponse(r=>r.url().endsWith('/anchors')&&r.request().method()==='POST');
  await action();
  const response=await responsePromise;
  assert.equal(response.status(),200,await response.text());
  return response.json();
};
const send=async text=>{
  await page.getByRole('textbox',{name:'论文问题'}).fill(text);
  const responsePromise=page.waitForResponse(r=>r.url().endsWith('/ask')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'发送',exact:true}).click();
  const response=await responsePromise;
  assert.equal(response.status(),200,await response.text());
  return response.json();
};
try{
  await page.goto(base,{waitUntil:'networkidle'});
  await page.locator('.paper-card').filter({hasText:'MonkeyOCR'}).first().click();
  await page.getByLabel('当前页').selectOption('1');
  const badge=page.locator('.pdf-object-badge').filter({hasText:'图 1'}).first();
  await badge.dblclick();
  await page.getByRole('button',{name:'柱子 43',exact:true}).click();
  assert.equal(await page.locator('.figure-detail-hit').count(),43);
  const firstBar=details.marks[0];
  const secondBar=details.marks[1];
  const barAnchor=await anchorFrom(()=>page.locator('.figure-detail-hit').first().click());
  assert.equal(barAnchor.kind,'bar');
  assert.equal(barAnchor.data.id,firstBar.id);
  await page.locator('.figure-detail-card').getByText(new RegExp(firstBar.value)).first().waitFor();
  await page.locator('.conversation-context').getByText(new RegExp(firstBar.series)).first().waitFor();
  const first=await send('阶段二浏览器测试：解释这根柱子');
  const followup=await send('阶段二浏览器测试：继续说明单位');
  assert.equal(first.anchor_id,barAnchor.id);
  assert.equal(followup.context_key,first.context_key);
  assert.deepEqual(followup.visual_box,barAnchor.bbox);
  const noteResponsePromise=page.waitForResponse(r=>r.url().endsWith('/notes')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'保存为笔记',exact:true}).last().click();
  const noteResponse=await noteResponsePromise;
  assert.equal(noteResponse.status(),200,await noteResponse.text());
  const pair=await anchorFrom(()=>page.locator('.figure-detail-hit').nth(1).click({modifiers:['Shift']}));
  assert.equal(pair.kind,'bar_pair');
  assert.deepEqual(new Set(pair.data.members.map(m=>m.id)),new Set([firstBar.id,secondBar.id]));
  await screenshot('phase23-bars-browser.png');
  await page.getByRole('button',{name:'图中文字 69',exact:true}).click();
  const token=await anchorFrom(()=>page.locator('.figure-detail-hit').first().click());
  assert.equal(token.kind,'token');
  assert.ok(token.data.text);
  await page.locator('.figure-detail-card').getByText(/局部 OCR|PDF 原生文字/).waitFor();
  await page.locator('.figure-viewer button[title="关闭"]').click();
  await page.getByLabel('当前页').selectOption('5');
  await page.locator('.pdf-object-badge').filter({hasText:'表 1'}).first().dblclick();
  await page.getByRole('button',{name:'单元格 101',exact:true}).click();
  const cell=await anchorFrom(()=>page.getByRole('button',{name:'D4LA [8] Language / ZH',exact:true}).click());
  assert.equal(cell.data.value,'');
  await page.locator('.figure-detail-card').getByText(/原表留空/).waitFor();
  const row=await anchorFrom(()=>page.getByRole('button',{name:'选整行',exact:true}).click());
  assert.equal(row.kind,'row');
  assert.equal(row.data.members.length,9);
  await anchorFrom(()=>page.getByRole('button',{name:'D4LA [8] Language / ZH',exact:true}).click());
  const column=await anchorFrom(()=>page.getByRole('button',{name:'选整列',exact:true}).click());
  assert.equal(column.kind,'column');
  assert.equal(column.data.members.length,10);
  await screenshot('phase23-table-browser.png');
  const csvResponse=await page.request.get(base+await page.getByRole('link',{name:'导出 CSV'}).getAttribute('href'));
  assert.equal(csvResponse.status(),200);
  const csv=await csvResponse.text();
  assert.match(csv,/D4LA/);
  assert.match(csv,/Language \/ ZH/);
  assert.match(csv,/MonkeyDoc/);
  const report=await page.request.get(base+'/api/documents/'+docId+'/reading-report?format=html');
  assert.equal(report.status(),200);
  const html=await report.text();
  assert.match(html,/data:image\/png;base64/);
  assert.match(html,/阶段二浏览器测试/);
  const inputs=await api('/__test/model-inputs');
  assert.equal(inputs.length,2);
  assert.equal(inputs[0].focus_region.local_detail.kind,'bar');
  assert.equal(inputs[1].previous_turns.at(-1).question,'阶段二浏览器测试：解释这根柱子');
  const after=await api('/api/documents/'+docId);
  assert.deepEqual(after.blocks,baseline.blocks);
  assert.deepEqual(after.notes.slice(0,baseline.notes.length),baseline.notes);
  assert.equal(after.notes.length,baseline.notes.length+1);
  assert.equal(after.notes.at(-1).anchor_id,barAnchor.id);
  assert.deepEqual(after.notes.at(-1).visual_box,barAnchor.bbox);
  assert.deepEqual(after.chats.slice(0,baseline.chats.length),baseline.chats);
  await page.locator('.figure-viewer button[title="关闭"]').click();
  await page.reload({waitUntil:'networkidle'});
  if(await page.locator('.paper-card').count())await page.locator('.paper-card').filter({hasText:'MonkeyOCR'}).first().click();
  await page.locator('.reader-toolbar').getByRole('button',{name:/^笔记/}).click();
  await page.locator('.note-card').last().getByRole('button',{name:/PDF 第 1 页/}).click();
  await page.locator('.conversation-context').getByText(new RegExp(firstBar.series)).first().waitFor();
  assert.equal(await page.getByLabel('当前页').inputValue(),'1');
  await page.locator('.pdf-manual-region').waitFor();
  await screenshot('phase23-restored-note-browser.png');
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('PASS: actual PDF 43 bars/69 tokens; single bar and paired bars; local token; fake QA/followup; table 90 cells+11 headers; blank cell/row/column; CSV and embedded-image reading report; note saved/reloaded/restored; existing blocks/notes/chats preserved.');
}catch(error){
  await screenshot('phase23-browser-failure.png');
  throw error;
}finally{await browser.close();}
